<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Authorize All Users..</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<!--
Template 2038 Carpet
http://www.tooplate.com/view/2038-carpet
-->
<link href="css/tooplate_style.css" rel="stylesheet" type="text/css" />

<link rel="stylesheet" type="text/css" href="css/contentslider.css" />
<script type="text/javascript" src="js/contentslider.js">

/***********************************************
* Featured Content Slider- (c) Dynamic Drive DHTML code library (www.dynamicdrive.com)
* This notice MUST stay intact for legal use
* Visit Dynamic Drive at http://www.dynamicdrive.com/ for this script and 100s more
***********************************************/

</script>

<style type="text/css">
<!--
.style1 {font-size: 4px}
.style2 {
	font-size: 27px;
	color: #00CC00;
}
.style12 {
	color: #0000FF;
	font-size: 26px;
}
.style22 {font-size: 16px; color: #FFFFFF; }
.style30 {color: #FFFFFF}
.style37 {font-size: 14px}
.style46 {color: #0000FF}
.style5 {color: #66CCFF;
	font-size: 21px;
	font-weight: bold;
}
.style15 {color: #FF00FF}
.style39 {color: #9900FF;
	font-weight: bold;
	font-size: 14px;
}
.style54 {font-size: 15px}
.style58 {color: #000000}
.style64 {color: #9900FF}
-->
</style>
</head>
<body>

<div id="tooplate_wrapper">
	<div id="tooplate_main_wrapper"><br/><h1 class="style2">Shadow Attacks based on Password Reuses: A Quantitative Empirical Analysis</h1>
		<div id="tooplate_header">
			<div class="h10" id="site_title"><h1 class="style1">&nbsp;</h1>
			</div>
			<div id="tooplate_menu">
				<ul>
					<li><a href="#"></a></li>
					<li><a href="#"></a></li>
					<li><a href="#"></a></li>
					<li><a href="#"></a></li>
					<li><a href="index.html">Home</a></li>
					<li><a href="UserLogin.jsp">User</a></li>
					<li><a href="ServerLogin.jsp" class="current">Admin</a></li>
					<li><a href="#"></a></li>
				</ul>    	
			</div> <!-- end of tooplate_menu -->
		</div> <!-- end of forever header -->
		
		<div id="tooplate_middle">
			<div id="mid_slider">
				<div id="slider1" class="sliderwrapper">
	
					<div class="contentdiv">
						<img src="images/slider/image_00.jpg" alt="Image 01" />
					</div>
		
					<div class="contentdiv">
						<img src="images/slider/image_01.jpg" alt="Image 02" />
					</div>            
					
					<div class="contentdiv">
						<img src="images/slider/image_02.jpg" alt="Image 03" />
					</div>
					
					<div class="contentdiv">
						<img src="images/slider/image_03.jpg" alt="Image 04" />
					</div>
				
				</div>
				
				<div id="paginate-slider1" class="pagination">
				
				</div>
				
				<script type="text/javascript">
				
				featuredcontentslider.init({
					id: "slider1",  //id of main slider DIV
					contentsource: ["inline", ""],  //Valid values: ["inline", ""] or ["ajax", "path_to_file"]
					toc: "#increment",  //Valid values: "#increment", "markup", ["label1", "label2", etc]
					nextprev: ["", ""],  //labels for "prev" and "next" links. Set to "" to hide.
					revealtype: "click", //Behavior of pagination links to reveal the slides: "click" or "mouseover"
					enablefade: [true, 0.2],  //[true/false, fadedegree]
					autorotate: [true, 3000],  //[true/false, pausetime]
					onChange: function(previndex, curindex){  //event handler fired whenever script changes slide
						//previndex holds index of last slide viewed b4 current (1=1st slide, 2nd=2nd etc)
						//curindex holds index of currently shown slide (1=1st slide, 2nd=2nd etc)
					}
				})
				
				</script>
			</div>
			
			<div id="mid_left">
				<div id="mid_title">Password-Based Authentication</div>
				<p>Password-based authentication  is one of the most
					widely used methods to authenticate a user before granting
					accesses to secured websites. 
				The wide adoption of
				  password-based authentication is the result of its low
				  cost and simplicity.</p>
		  </div>
			<div class="cleaner"></div>
		</div> <!-- end of middle -->
		
		<div id="tooplate_main_top"></div>
		<div id="tooplate_main">
			
			<div class="col_w900 col">
			  <div class="col_allw280 fp_service_box">
			    <form id="form1" name="form1" method="post" action="ServerAuthentication.jsp">
                          <h3><span class="style12">Authorize All Users..</span></h3>
                          <p>&nbsp;</p>
                          <table width="896" border="1" align="center"  cellpadding="0" cellspacing="0"  ">
                            <tr>
                              <td  width="63"  valign="middle" height="34" style="color: #2c83b0;"><div align="center" class="style5 style54 style64">Si No. </div></td>
                              <td  width="146" valign="middle" height="34" style="color: #2c83b0;"><div align="center" class="style5 style54 style64">User Image</div></td>
                              <td  width="127" valign="middle" height="34" style="color: #2c83b0;"><div align="center" class="style5 style54 style64">Username</div></td>
                              <td  width="116" valign="middle" style="color: #2c83b0;"><div align="center" class="style5 style54 style64">Password</div></td>
                              <td  width="145" valign="middle" height="34" style="color: #2c83b0;"><div align="center" class="style5 style54 style64">Email</div></td>
                              <td  width="146" valign="middle" height="34" style="color: #2c83b0;"><div align="center" class="style5 style54 style64">Site</div></td>
                              <td  width="118"  valign="middle" height="34" style="color: #2c83b0;"><div align="center" class="style5 style54 style64">Status</div></td>
                            </tr>
                            <%@ include file="connect.jsp" %>
                            <%
					  
						String s1,s2,s3,s4,s5,s6,s7,s8;
						int i=0;
						try 
						{
						   	String query="select * from user"; 
						   	Statement st=connection.createStatement();
						   	ResultSet rs=st.executeQuery(query);
					   		while ( rs.next() )
					   		{
								i=rs.getInt(1);
								s1=rs.getString(2);
								s8=rs.getString(3);
								s2=rs.getString(4);
								s3=rs.getString(7);
								s4=rs.getString(5);
								s5=rs.getString(10);
								s6=rs.getString(9);
								s7=rs.getString(11);
							
								
								
								
								
							
						
					%>
                            <tr>
                              <td height="0" align="center"  valign="middle"><p class="style22 style5 style37 style58">&nbsp;</p>
                                  <div align="center" class="style22 style5 style37 style58"> <span class="style37">
                                    <%out.println(i);%>
                                    </span>
                                      <p class="style37">&nbsp; </p>
                                  </div></td>
                              <td width="146" rowspan="1" align="center" valign="middle" ><div class="style22 style5 style37 style58" style="margin:10px 13px 10px 13px;" >
                                  <div align="left"><a class="#" id="img1" href="#" >
                                    <input  name="image" type="image" src="user_Pic.jsp?id=<%=i%>" style="width:120px; height:120px;" />
                                  </a> </div>
                              </div></td>
                              <td height="0" align="center"  valign="middle"><div align="center" class="style22 style5 style20 style37 style58"> <span class="style37">
                                    <%out.println(s1);%>
                                  </span></div></td>
                              <td align="center"  valign="middle"><div align="center" class="style22 style5 style20 style37 style58"> <span class="style37">
                                <%out.println(s8);%>
                                </span></div></td>
                              <td height="0" align="center"  valign="middle"><p class="style22 style5 style20 style37 style58">&nbsp;</p>
                                  <div align="center" class="style22 style5 style20 style37 style58"> <span class="style37">
                                    <%out.println(s2);%>
                                    </span>
                                      <p class="style37">&nbsp;</p>
                                  </div></td>
                              <td height="0" align="center"  valign="middle"><p class="style22 style5 style20 style37 style58">&nbsp;</p>
                                  <div align="center" class="style22 style5 style20 style37 style58"> <span class="style37">
                                    <%out.println(s5);%>
                                    </span>
                                      <p class="style37">&nbsp; </p>
                                  </div></td>
                              <%
						if(s6.equalsIgnoreCase("waiting"))
						{
						
						%>
                              <td valign="middle" height="0" style="color:#000000;"align="center"><div align="center" class="style22 style5 style20 style30 style37">
                                  <div align="center" class="style20 style37 style46">
                                    <p><strong><a href="S_UserStatus.jsp?id=<%=i%>" class="style46"></a></strong></p>
                                    <p><a href="S_UserStatus.jsp?id=<%=i%>" class="style46"><strong>waiting</strong></a></p>
                                  </div>
                              </div></td>
                              <%
						}
						else
						{
						%>
                              <td width="17" height="0" align="center"  valign="middle"><div align="center" class="style22 style5 style20 style37 style15"> <span class="style37">
                                  <%out.println(s6);%>
                              </span> </div></td>
                              <%
						}
						
						%>
                            </tr>
                            <%
						}
						
					
				
						connection.close();
					}
					catch(Exception e)
					{
						out.println(e.getMessage());
					}
					%>
                          </table>
			    </form>
	          </div>
			  <div class="cleaner h60"></div>
			        <div class="cleaner">
			          <div align="right"><a href="ServerMain.jsp" class="style39"><strong>Back</strong></a> </div>
			        </div>
		  </div>
			
				<div class="col_w900 col_w900_last">
					<div class="con_tit_01"><strong>Password-Based Authentication</strong></div>
					<img src="images/tooplate_image_01.png" alt="Image 01" class="image_wrapper image_fl" />
					<p align="justify"><strong>Password-Based Authentication </strong>is one of the most 
					  widely used methods to authenticate a user before granting 
					  accesses to secured websites. The wide adoption of 
					  password-based authentication is the result of its low 
					  cost and simplicity: a user can enter his or her passwords 
					  anywhere by a keyboard or a touch screen without any 
					  other extra devices. The popularity of passwords and 
					  the proliferation of websites, however, lead to a concern 
					  on password reuses between accounts on different websites or even on the same websites.</p>
					<div class="cleaner"></div>
				</div>
			
			<div class="cleaner"></div>
		</div> <!-- end of main -->
		<div id="tooplate_main_bot"></div>
		
		<div id="tooplate_footer"></div>
	</div> <!-- main wrapper -->
</div> <!-- wrapper  -->

</body>
</html>