<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Friends Details..</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<!--
Template 2038 Carpet
http://www.tooplate.com/view/2038-carpet
-->
<link href="css/tooplate_style.css" rel="stylesheet" type="text/css" />

<link rel="stylesheet" type="text/css" href="css/contentslider.css" />
<script type="text/javascript" src="js/contentslider.js">

/***********************************************
* Featured Content Slider- (c) Dynamic Drive DHTML code library (www.dynamicdrive.com)
* This notice MUST stay intact for legal use
* Visit Dynamic Drive at http://www.dynamicdrive.com/ for this script and 100s more
***********************************************/

</script>

<style type="text/css">
<!--
.style1 {font-size: 4px}
.style2 {
	font-size: 27px;
	color: #00CC00;
}
.style3 {font-size: 23px}
.style31 {	color: #FF00FF;
	font-size: 24px;
}
.style52 {
	font-size: 16px;
	color: #000000;
}
.style39 {color: #9900FF;
	font-weight: bold;
	font-size: 14px;
}
.style34 {font-size: 18px; color: #00FF00; }
.style36 {font-size: 18px; color: #FF3300; }
.style60 {font-size: 13px}
.style61 {font-size: 13px;
	color: #000000;
}
.style63 {font-size: 15px;
	color: #0000FF;
	font-weight: bold;
}
.style64 {color: #00FF00}
.style66 {color: #000000}
.style67 {font-family: "Times New Roman", Times, serif}
.style68 {color: #FFFFFF}
.style69 {font-size: 15px}
.style7 {font-size: 30px;
	color: #6699CC;
	font-weight: bold;
	font-family: "Courier New", Courier, monospace;
}
.style71 {color: #CCCCCC}
.style73 {
	font-size: 14px;
	font-weight: bold;
}
.style40 {color: #FF3300}
.style74 {font-size: 22.5px}
.style75 {font-size: 14px}
-->
</style>
</head>
<body>

<div id="tooplate_wrapper">
	<div id="tooplate_main_wrapper"><br/><h1 class="style2">Shadow Attacks based on Password Reuses: A Quantitative Empirical Analysis</h1>
		<div id="tooplate_header">
			<div class="h10" id="site_title"><h1 class="style1">&nbsp;</h1>
			</div>
			<div id="tooplate_menu">
				<ul>
					<li><a href="#"></a></li>
					<li><a href="#"></a></li>
					<li><a href="#"></a></li>
					<li><a href="#"></a></li>
					<li><a href="index.html">Home</a></li>
					<li><a href="UserLogin.jsp">User</a></li>
					<li><a href="ServerLogin.jsp" class="current">Admin</a></li>
					<li><a href="#"></a></li>
				</ul>    	
			</div> <!-- end of tooplate_menu -->
		</div> <!-- end of forever header -->
		
		<div id="tooplate_middle">
			<div id="mid_slider">
				<div id="slider1" class="sliderwrapper">
	
					<div class="contentdiv">
						<img src="images/slider/image_00.jpg" alt="Image 01" />
					</div>
		
					<div class="contentdiv">
						<img src="images/slider/image_01.jpg" alt="Image 02" />
					</div>            
					
					<div class="contentdiv">
						<img src="images/slider/image_02.jpg" alt="Image 03" />
					</div>
					
					<div class="contentdiv">
						<img src="images/slider/image_03.jpg" alt="Image 04" />
					</div>
				
				</div>
				
				<div id="paginate-slider1" class="pagination">
				
				</div>
				
				<script type="text/javascript">
				
				featuredcontentslider.init({
					id: "slider1",  //id of main slider DIV
					contentsource: ["inline", ""],  //Valid values: ["inline", ""] or ["ajax", "path_to_file"]
					toc: "#increment",  //Valid values: "#increment", "markup", ["label1", "label2", etc]
					nextprev: ["", ""],  //labels for "prev" and "next" links. Set to "" to hide.
					revealtype: "click", //Behavior of pagination links to reveal the slides: "click" or "mouseover"
					enablefade: [true, 0.2],  //[true/false, fadedegree]
					autorotate: [true, 3000],  //[true/false, pausetime]
					onChange: function(previndex, curindex){  //event handler fired whenever script changes slide
						//previndex holds index of last slide viewed b4 current (1=1st slide, 2nd=2nd etc)
						//curindex holds index of currently shown slide (1=1st slide, 2nd=2nd etc)
					}
				})
				
				</script>
			</div>
			
			<div id="mid_left">
				<div id="mid_title">Password-Based Authentication</div>
				<p>Password-based authentication  is one of the most
					widely used methods to authenticate a user before granting
					accesses to secured websites. 
				The wide adoption of
				  password-based authentication is the result of its low
				  cost and simplicity.</p>
		  </div>
			<div class="cleaner"></div>
		</div> <!-- end of middle -->
		
		<div id="tooplate_main_top"></div>
		<div id="tooplate_main">
			
			<div class="col_w900 col">
			  <div class="col_allw280 fp_service_box">
			    <table width="431" border="0" cellspacing="2" cellpadding="2">
                            <tr>
                              <td width="423"><span class="style31">Friends in Similar Sites..</span></td>
                            </tr>
                </table>
                          <p>&nbsp;</p>
                          <table width="828" border="1" align="center">
                            <tr>
                              <td width="45" height="47" align="center" valign="middle"><div align="center" class="style63"><span class="style68">Si No.</span> </div></td>
                              <td width="105" align="center" valign="middle"><div align="center" class="style36 style69 style40"><strong>Request From </strong></div></td>
                              <td width="130" align="center" valign="middle"><div align="center" class="style36 style69 style40"><strong>Requested User </strong></div></td>
                              <td width="115" align="center" valign="middle"><div align="center" class="style36 style40 style69"><strong>Social Site </strong></div></td>
                              <td width="120" align="center" valign="middle"><div align="center" class="style34 style65 style69"><strong>Request To </strong></div></td>
                              <td width="132" align="center" valign="middle"><div align="center" class="style36 style65 style69 style64"><strong> Request To Name </strong></div></td>
                              <td width="135" align="center" valign="middle"><div align="center" class="style36 style65 style69 style64"><strong>Social Site </strong></div></td>
                            </tr>
                            <%@ include file="connect.jsp" %>
                            <%@ page import="java.io.*"%>
                            <%@ page import="java.util.*" %>
                            <%@ page import="java.util.Date" %>
                            <%@ page import="com.oreilly.servlet.*"%>
                            <%@ page import ="java.text.SimpleDateFormat" %>
                            <%
 
      	
	String s1="",s2="",s3="",s4="",s5="",s6="",s7="",s8,s9,s10,s11,s12,s13;
	int i=0,j=1,k=0;

     try 
	{
          		       String site1=request.getParameter("site");
	
					   String query="select * from  frequest where ((fromsite='"+site1+"' and tosite='"+site1+"') and status='Accepted')"; 
					   Statement st=connection.createStatement();
					   ResultSet rs=st.executeQuery(query);
					   while( rs.next() )
					   {
						
						
								s2=rs.getString(2);
								s3=rs.getString(3);
								s4=rs.getString(6);
								s5=rs.getString(7);
								
								
				
								
		
%>
                            <tr>
                              <td height="111"><div align="center" class="style71 style66 style73">
                                  <div align="center"  class="style72 style68 style67"><%=j%></div>
                              </div>
                                  <div align="center" class="style39 style40 style7 style60 style66"></div></td>
                              <td><div align="center" class="style61">
                                  <input  name="image" type="image" src="user_Pic2.jsp?name=<%=s2%>&amp;site1=<%=site1%>" width="100" height="100" alt="Submit" />
                              </div></td>
                              <td><div align="center" class="style72 style67 style75 style66"><strong><%=s2 %></strong></div></td>
                              <td><div align="center" class="style72 style67 style75 style66"><strong><%=s4 %></strong></div></td>
                              <td><div align="center" class="style52 style66 style67 style68 style66 style66">
                                  <input  name="image2" type="image" src="user_Pic2.jsp?name=<%=s3%>&amp;site1=<%=site1%>" width="100" height="100" alt="Submit" />
                              </div></td>
                              <td><div align="center" class="style67 style72 style75 style66"><strong><%=s3 %></strong></div></td>
                              <td><div align="center" class="style67 style72 style75 style66"><strong><%=s5 %></strong></div></td>
                            </tr>
                            <%
		 
		j++;
	  		}
	 

           connection.close();
          }
         
          catch(Exception e)
          {
            out.println(e.getMessage());
          }
%>
                          </table>
                          <p>&nbsp;</p>
			              <table width="543" border="0" cellspacing="2" cellpadding="2">
                            <tr>
                              <td width="535"><div align="right"><a href="S_FriendsInSameSite.jsp" class="style39"><strong>Back</strong></a></div></td>
                            </tr>
                          </table>
              </div>
			  <div class="cleaner h60"></div>
			  <div class="col_allw280 fp_service_box">
						<div class="con_tit_02 style3">Intra-Site Password Reuses </div>
						<img src="images/onebit_18.png" alt="Image" />
						<p align="justify">A user creates accounts with the same password on 
                          the same websites  is referred as (ISPR).</p>
                        <p align="justify">&nbsp;</p>
			  </div>
			  <div class="col_allw280 fp_service_box">
			    <div class="con_tit_02 style74">Cross-Site Password Reuses</div>
                <img src="images/onebit_15.png" alt="Image" />
                <p> A user creates accounts with the 
                  same password across different websites is referred as (CSPR).</p>
                <p align="justify">&nbsp;</p>
		      </div>
			  <div class="col_allw280 fp_service_box col_last">
						<div class="con_tit_02 style3">Concepts</div>
						<p>Password, Quantitative.</p>
						<p>Shadow Attack, Empirical Analysis.</p>
					    <p>Intra-Site &amp; Cross-Site Password Reuses.</p>
		      </div>
					
					<div class="cleaner"></div>
		  </div>
			
				<div class="col_w900 col_w900_last">
					<div class="con_tit_01"><strong>Password-Based Authentication</strong></div>
					<img src="images/tooplate_image_01.png" alt="Image 01" class="image_wrapper image_fl" />
					<p align="justify"><strong>Password-Based Authentication </strong>is one of the most 
					  widely used methods to authenticate a user before granting 
					  accesses to secured websites. The wide adoption of 
					  password-based authentication is the result of its low 
					  cost and simplicity: a user can enter his or her passwords 
					  anywhere by a keyboard or a touch screen without any 
					  other extra devices. The popularity of passwords and 
					  the proliferation of websites, however, lead to a concern 
					  on password reuses between accounts on different websites or even on the same websites.</p>
					<div class="cleaner"></div>
				</div>
			
			<div class="cleaner"></div>
		</div> <!-- end of main -->
		<div id="tooplate_main_bot"></div>
		
		<div id="tooplate_footer"></div>
	</div> <!-- main wrapper -->
</div> <!-- wrapper  -->

</body>
</html>