<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Friends in Cross Sites..</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<!--
Template 2038 Carpet
http://www.tooplate.com/view/2038-carpet
-->
<link href="css/tooplate_style.css" rel="stylesheet" type="text/css" />

<link rel="stylesheet" type="text/css" href="css/contentslider.css" />
<script type="text/javascript" src="js/contentslider.js">

/***********************************************
* Featured Content Slider- (c) Dynamic Drive DHTML code library (www.dynamicdrive.com)
* This notice MUST stay intact for legal use
* Visit Dynamic Drive at http://www.dynamicdrive.com/ for this script and 100s more
***********************************************/

</script>

<style type="text/css">
<!--
.style1 {font-size: 4px}
.style2 {
	font-size: 27px;
	color: #00CC00;
}
.style31 {	color: #FF00FF;
	font-size: 24px;
}
.style39 {color: #9900FF;
	font-weight: bold;
	font-size: 14px;
}
.style36 {font-size: 18px; color: #FF3300; }
.style61 {
	font-size: 13px;
	color: #000000;
	font-weight: bold;
}
.style63 {font-size: 14px;
	color: #0000FF;
	font-weight: bold;
}
.style64 {color: #00FF00}
.style66 {color: #000000}
.style68 {color: #FFFFFF}
.style7 {font-size: 30px;
	color: #000000;
	font-weight: bold;
	font-family: "Courier New", Courier, monospace;
}
.style73 {font-size: 13px}
.style40 {color: #FF3300}
.style41 {color: #000000;
	font-weight: bold;
}
.style41 {font-size: 14px; color: #FFFFFF; }
.style55 {color: #FF0000}
.style72 {font-size: 14px}
.style42 {font-size: 12px}
-->
</style>
</head>
<body>

<div id="tooplate_wrapper">
	<div id="tooplate_main_wrapper"><br/><h1 class="style2">Shadow Attacks based on Password Reuses: A Quantitative Empirical Analysis</h1>
		<div id="tooplate_header">
			<div class="h10" id="site_title"><h1 class="style1">&nbsp;</h1>
			</div>
			<div id="tooplate_menu">
				<ul>
					<li><a href="#"></a></li>
					<li><a href="#"></a></li>
					<li><a href="#"></a></li>
					<li><a href="#"></a></li>
					<li><a href="index.html">Home</a></li>
					<li><a href="UserLogin.jsp">User</a></li>
					<li><a href="ServerLogin.jsp" class="current">Admin</a></li>
					<li><a href="#"></a></li>
				</ul>    	
			</div> <!-- end of tooplate_menu -->
		</div> <!-- end of forever header -->
		
		<div id="tooplate_middle">
			<div id="mid_slider">
				<div id="slider1" class="sliderwrapper">
	
					<div class="contentdiv">
						<img src="images/slider/image_00.jpg" alt="Image 01" />
					</div>
		
					<div class="contentdiv">
						<img src="images/slider/image_01.jpg" alt="Image 02" />
					</div>            
					
					<div class="contentdiv">
						<img src="images/slider/image_02.jpg" alt="Image 03" />
					</div>
					
					<div class="contentdiv">
						<img src="images/slider/image_03.jpg" alt="Image 04" />
					</div>
				
				</div>
				
				<div id="paginate-slider1" class="pagination">
				
				</div>
				
				<script type="text/javascript">
				
				featuredcontentslider.init({
					id: "slider1",  //id of main slider DIV
					contentsource: ["inline", ""],  //Valid values: ["inline", ""] or ["ajax", "path_to_file"]
					toc: "#increment",  //Valid values: "#increment", "markup", ["label1", "label2", etc]
					nextprev: ["", ""],  //labels for "prev" and "next" links. Set to "" to hide.
					revealtype: "click", //Behavior of pagination links to reveal the slides: "click" or "mouseover"
					enablefade: [true, 0.2],  //[true/false, fadedegree]
					autorotate: [true, 3000],  //[true/false, pausetime]
					onChange: function(previndex, curindex){  //event handler fired whenever script changes slide
						//previndex holds index of last slide viewed b4 current (1=1st slide, 2nd=2nd etc)
						//curindex holds index of currently shown slide (1=1st slide, 2nd=2nd etc)
					}
				})
				
				</script>
			</div>
			
			<div id="mid_left">
				<div id="mid_title">Password-Based Authentication</div>
				<p>Password-based authentication  is one of the most
					widely used methods to authenticate a user before granting
					accesses to secured websites. 
				The wide adoption of
				  password-based authentication is the result of its low
				  cost and simplicity.</p>
		  </div>
			<div class="cleaner"></div>
		</div> <!-- end of middle -->
		
		<div id="tooplate_main_top"></div>
		<div id="tooplate_main">
			
			<div class="col_w900 col">
			  <div class="col_allw280 fp_service_box">
			    <table width="431" border="0" cellspacing="2" cellpadding="2">
                            <tr>
                              <td width="423"><span class="style31">Friends in Cross Sites..</span></td>
                            </tr>
                </table>
                          <p>&nbsp;</p>
                          <table width="893" border="1" align="center">
                            <tr>
                              <td width="46" height="47" align="center" valign="middle"><div align="center" class="style63 style42"><span class="style68">Si No.</span></div></td>
                              <td width="120" align="center" valign="middle"><div align="center" class="style59 style36 style64 style83 style72"><strong>Request From </strong></div></td>
                              <td width="147" align="center" valign="middle"><div align="center" class="style59 style36 style64 style83 style72"><strong>Requested User </strong></div></td>
                              <td width="118" align="center" valign="middle"><div align="center" class="style59 style36 style64 style83 style72"><strong>Social Site </strong></div></td>
                              <td width="120" align="center" valign="middle"><div align="center" class="style59 style36 style55 style83 style72"><strong>Request To </strong></div></td>
                              <td width="152" align="center" valign="middle"><div align="center" class="style59 style36 style55 style83 style72"><strong> Request To Name </strong></div></td>
                              <td width="144" align="center" valign="middle"><div align="center" class="style59 style36 style55 style83 style72"><strong>Social Site </strong></div></td>
                            </tr>
                            <%@page import="com.oreilly.servlet.*,java.sql.*,java.lang.*,java.text.SimpleDateFormat,java.util.*,java.io.*,javax.servlet.*, javax.servlet.http.*" %>
                            <%@ page import="java.sql.*"%>
                            <%@ include file="connect.jsp" %>
                            <%@ page import="java.util.Date" %>
                            <%
 
      	
	String s1="",s22="",s3="",s4="",s5="",s6="",s7="",s8,s9,s10,s11,s12,s13;
	int i=1,j=0,k=0;

     try 
	{
           
					   String query="select distinct(site) from  user"; 
					   Statement st=connection.createStatement();
					   ResultSet rs=st.executeQuery(query);
					   while( rs.next() )
					   {
						
						
								s22=rs.getString(1);

								String query1="select * from frequest where (fromsite='"+s22+"' and tosite!='"+s22+"') and status='Accepted'"; 
								Statement st1=connection.createStatement();
								ResultSet rs1=st1.executeQuery(query1);
							 	while( rs1.next() )
							 	{
								
									String u1=rs1.getString(2); 
									String u2=rs1.getString(3); 
									String ss1=rs1.getString(6); 
									String ss2=rs1.getString(7); 
							
								
%>
                            <tr>
                              <td height="124"><div align="center" class="style41">
                                  <div align="center" class="sstyle72 style73"><%=i%></div>
                              </div>
                                  <div align="center" class="style39 style40 style7 style66"></div></td>
                              <td><div align="center" class="style66 style41"><strong>
                                <input  name="image" type="image" src="user_Pic2.jsp?name=<%=u1%>&amp;site1=<%=ss1%>" width="120" height="120" alt="Submit" />
                              </strong></div></td>
                              <td><div align="center" class="style66 style73"><strong><%=u1%></strong></div></td>
                              <td><div align="center" class="style66 style73"><strong><%=ss1%></strong></div></td>
                              <td><div align="center" class="style61 style66">
                                  <input  name="image2" type="image" src="user_Pic2.jsp?name=<%=u2%>&amp;site1=<%=ss2%>" width="120" height="120" alt="Submit" />
                              </div></td>
                              <td><div align="center" class="style66 style73"><strong><%=u2%></strong></div></td>
                              <td><div align="center" class="style66 style73"><strong><%=ss2%></strong></div></td>
                            </tr>
                            <%
		 i++; }
	  }
		
	
	 

           connection.close();
          }
         
          catch(Exception e)
          {
            out.println(e.getMessage());
          }
%>
                          </table>
                          <p>&nbsp;</p>
			              <table width="444" border="0" cellspacing="2" cellpadding="2">
                            <tr>
                              <td width="462"><div align="right"><a href="ServerMain.jsp" class="style39"><strong>Back</strong></a></div></td>
                            </tr>
                          </table>
              </div>
			  <div class="cleaner"></div>
		  </div>
			
				<div class="col_w900 col_w900_last">
					<div class="con_tit_01"><strong>Password-Based Authentication</strong></div>
					<img src="images/tooplate_image_01.png" alt="Image 01" class="image_wrapper image_fl" />
					<p align="justify"><strong>Password-Based Authentication </strong>is one of the most 
					  widely used methods to authenticate a user before granting 
					  accesses to secured websites. The wide adoption of 
					  password-based authentication is the result of its low 
					  cost and simplicity: a user can enter his or her passwords 
					  anywhere by a keyboard or a touch screen without any 
					  other extra devices. The popularity of passwords and 
					  the proliferation of websites, however, lead to a concern 
					  on password reuses between accounts on different websites or even on the same websites.</p>
					<div class="cleaner"></div>
				</div>
			
			<div class="cleaner"></div>
		</div> <!-- end of main -->
		<div id="tooplate_main_bot"></div>
		
		<div id="tooplate_footer"></div>
	</div> <!-- main wrapper -->
</div> <!-- wrapper  -->

</body>
</html>